services: 
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE}

    volumes: 
      - pgurlprojectdata:/var/lib/postgresql/data
    ports:
      - ${PG_PORT}:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    environment:
      PG_HOST: ${PG_HOST}

volumes:
  pgurlprojectdata: